// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `sessions`, `snapshot`, `step_to_bridge`, `value_to_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

BigInt playerOpen({required String path}) =>
    RustLib.instance.api.crateApiPlayerPlayerOpen(path: path);

BigInt playerOpenRaw({required String source}) =>
    RustLib.instance.api.crateApiPlayerPlayerOpenRaw(source: source);

bool playerClose({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiPlayerPlayerClose(sessionId: sessionId);

BridgeState playerAdvance({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiPlayerPlayerAdvance(sessionId: sessionId);

BridgeState playerChoose({required BigInt sessionId, required int index}) =>
    RustLib.instance.api.crateApiPlayerPlayerChoose(
      sessionId: sessionId,
      index: index,
    );

BridgeState playerGetState({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiPlayerPlayerGetState(sessionId: sessionId);

class BridgeChoice {
  final String text;
  final String target;

  const BridgeChoice({required this.text, required this.target});

  @override
  int get hashCode => text.hashCode ^ target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeChoice &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          target == other.target;
}

class BridgeState {
  final BigInt sessionId;
  final String scriptName;
  final String scene;
  final String? bg;
  final String? bgm;
  final bool finished;
  final List<BridgeVariable> variables;
  final BridgeStep? current;
  final List<BridgeStep> history;

  const BridgeState({
    required this.sessionId,
    required this.scriptName,
    required this.scene,
    this.bg,
    this.bgm,
    required this.finished,
    required this.variables,
    this.current,
    required this.history,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      scriptName.hashCode ^
      scene.hashCode ^
      bg.hashCode ^
      bgm.hashCode ^
      finished.hashCode ^
      variables.hashCode ^
      current.hashCode ^
      history.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeState &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          scriptName == other.scriptName &&
          scene == other.scene &&
          bg == other.bg &&
          bgm == other.bgm &&
          finished == other.finished &&
          variables == other.variables &&
          current == other.current &&
          history == other.history;
}

class BridgeStep {
  final String kind;
  final String? text;
  final String? actorName;
  final String? actorId;
  final String? emotion;
  final String? position;
  final List<BridgeChoice> choices;

  const BridgeStep({
    required this.kind,
    this.text,
    this.actorName,
    this.actorId,
    this.emotion,
    this.position,
    required this.choices,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      text.hashCode ^
      actorName.hashCode ^
      actorId.hashCode ^
      emotion.hashCode ^
      position.hashCode ^
      choices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStep &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          actorName == other.actorName &&
          actorId == other.actorId &&
          emotion == other.emotion &&
          position == other.position &&
          choices == other.choices;
}

class BridgeVariable {
  final String name;
  final String value;

  const BridgeVariable({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeVariable &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}
