// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/player.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeStep dco_decode_box_autoadd_bridge_step(dynamic raw);

  @protected
  BridgeChoice dco_decode_bridge_choice(dynamic raw);

  @protected
  BridgeState dco_decode_bridge_state(dynamic raw);

  @protected
  BridgeStep dco_decode_bridge_step(dynamic raw);

  @protected
  BridgeVariable dco_decode_bridge_variable(dynamic raw);

  @protected
  List<BridgeChoice> dco_decode_list_bridge_choice(dynamic raw);

  @protected
  List<BridgeStep> dco_decode_list_bridge_step(dynamic raw);

  @protected
  List<BridgeVariable> dco_decode_list_bridge_variable(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BridgeStep? dco_decode_opt_box_autoadd_bridge_step(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeStep sse_decode_box_autoadd_bridge_step(SseDeserializer deserializer);

  @protected
  BridgeChoice sse_decode_bridge_choice(SseDeserializer deserializer);

  @protected
  BridgeState sse_decode_bridge_state(SseDeserializer deserializer);

  @protected
  BridgeStep sse_decode_bridge_step(SseDeserializer deserializer);

  @protected
  BridgeVariable sse_decode_bridge_variable(SseDeserializer deserializer);

  @protected
  List<BridgeChoice> sse_decode_list_bridge_choice(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeStep> sse_decode_list_bridge_step(SseDeserializer deserializer);

  @protected
  List<BridgeVariable> sse_decode_list_bridge_variable(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BridgeStep? sse_decode_opt_box_autoadd_bridge_step(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_step(
    BridgeStep self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_choice(BridgeChoice self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_state(BridgeState self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_step(BridgeStep self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_variable(
    BridgeVariable self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_choice(
    List<BridgeChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_step(
    List<BridgeStep> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_variable(
    List<BridgeVariable> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_step(
    BridgeStep? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
