// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/player.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -984045137;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'storyscript_player_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  BridgeState crateApiPlayerPlayerAdvance({required BigInt sessionId});

  BridgeState crateApiPlayerPlayerChoose({
    required BigInt sessionId,
    required int index,
  });

  bool crateApiPlayerPlayerClose({required BigInt sessionId});

  BridgeState crateApiPlayerPlayerGetState({required BigInt sessionId});

  BigInt crateApiPlayerPlayerOpen({required String path});

  BigInt crateApiPlayerPlayerOpenRaw({required String source});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  BridgeState crateApiPlayerPlayerAdvance({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerAdvanceConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerAdvanceConstMeta =>
      const TaskConstMeta(debugName: "player_advance", argNames: ["sessionId"]);

  @override
  BridgeState crateApiPlayerPlayerChoose({
    required BigInt sessionId,
    required int index,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_32(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerChooseConstMeta,
        argValues: [sessionId, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerChooseConstMeta => const TaskConstMeta(
    debugName: "player_choose",
    argNames: ["sessionId", "index"],
  );

  @override
  bool crateApiPlayerPlayerClose({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerPlayerCloseConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerCloseConstMeta =>
      const TaskConstMeta(debugName: "player_close", argNames: ["sessionId"]);

  @override
  BridgeState crateApiPlayerPlayerGetState({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerGetStateConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerGetStateConstMeta =>
      const TaskConstMeta(
        debugName: "player_get_state",
        argNames: ["sessionId"],
      );

  @override
  BigInt crateApiPlayerPlayerOpen({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerOpenConstMeta =>
      const TaskConstMeta(debugName: "player_open", argNames: ["path"]);

  @override
  BigInt crateApiPlayerPlayerOpenRaw({required String source}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerOpenRawConstMeta,
        argValues: [source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerOpenRawConstMeta =>
      const TaskConstMeta(debugName: "player_open_raw", argNames: ["source"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeStep dco_decode_box_autoadd_bridge_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_step(raw);
  }

  @protected
  BridgeChoice dco_decode_bridge_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeChoice(
      text: dco_decode_String(arr[0]),
      target: dco_decode_String(arr[1]),
    );
  }

  @protected
  BridgeState dco_decode_bridge_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return BridgeState(
      sessionId: dco_decode_u_64(arr[0]),
      scriptName: dco_decode_String(arr[1]),
      scene: dco_decode_String(arr[2]),
      bg: dco_decode_opt_String(arr[3]),
      bgm: dco_decode_opt_String(arr[4]),
      finished: dco_decode_bool(arr[5]),
      variables: dco_decode_list_bridge_variable(arr[6]),
      current: dco_decode_opt_box_autoadd_bridge_step(arr[7]),
      history: dco_decode_list_bridge_step(arr[8]),
    );
  }

  @protected
  BridgeStep dco_decode_bridge_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BridgeStep(
      kind: dco_decode_String(arr[0]),
      text: dco_decode_opt_String(arr[1]),
      actorName: dco_decode_opt_String(arr[2]),
      actorId: dco_decode_opt_String(arr[3]),
      emotion: dco_decode_opt_String(arr[4]),
      position: dco_decode_opt_String(arr[5]),
      choices: dco_decode_list_bridge_choice(arr[6]),
    );
  }

  @protected
  BridgeVariable dco_decode_bridge_variable(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeVariable(
      name: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<BridgeChoice> dco_decode_list_bridge_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_choice).toList();
  }

  @protected
  List<BridgeStep> dco_decode_list_bridge_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_step).toList();
  }

  @protected
  List<BridgeVariable> dco_decode_list_bridge_variable(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_variable).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BridgeStep? dco_decode_opt_box_autoadd_bridge_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bridge_step(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeStep sse_decode_box_autoadd_bridge_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_step(deserializer));
  }

  @protected
  BridgeChoice sse_decode_bridge_choice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_target = sse_decode_String(deserializer);
    return BridgeChoice(text: var_text, target: var_target);
  }

  @protected
  BridgeState sse_decode_bridge_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_64(deserializer);
    var var_scriptName = sse_decode_String(deserializer);
    var var_scene = sse_decode_String(deserializer);
    var var_bg = sse_decode_opt_String(deserializer);
    var var_bgm = sse_decode_opt_String(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_variables = sse_decode_list_bridge_variable(deserializer);
    var var_current = sse_decode_opt_box_autoadd_bridge_step(deserializer);
    var var_history = sse_decode_list_bridge_step(deserializer);
    return BridgeState(
      sessionId: var_sessionId,
      scriptName: var_scriptName,
      scene: var_scene,
      bg: var_bg,
      bgm: var_bgm,
      finished: var_finished,
      variables: var_variables,
      current: var_current,
      history: var_history,
    );
  }

  @protected
  BridgeStep sse_decode_bridge_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_actorName = sse_decode_opt_String(deserializer);
    var var_actorId = sse_decode_opt_String(deserializer);
    var var_emotion = sse_decode_opt_String(deserializer);
    var var_position = sse_decode_opt_String(deserializer);
    var var_choices = sse_decode_list_bridge_choice(deserializer);
    return BridgeStep(
      kind: var_kind,
      text: var_text,
      actorName: var_actorName,
      actorId: var_actorId,
      emotion: var_emotion,
      position: var_position,
      choices: var_choices,
    );
  }

  @protected
  BridgeVariable sse_decode_bridge_variable(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return BridgeVariable(name: var_name, value: var_value);
  }

  @protected
  List<BridgeChoice> sse_decode_list_bridge_choice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeChoice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_choice(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeStep> sse_decode_list_bridge_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeStep>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_step(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeVariable> sse_decode_list_bridge_variable(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeVariable>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_variable(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeStep? sse_decode_opt_box_autoadd_bridge_step(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_step(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bridge_step(
    BridgeStep self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_step(self, serializer);
  }

  @protected
  void sse_encode_bridge_choice(BridgeChoice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.target, serializer);
  }

  @protected
  void sse_encode_bridge_state(BridgeState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sessionId, serializer);
    sse_encode_String(self.scriptName, serializer);
    sse_encode_String(self.scene, serializer);
    sse_encode_opt_String(self.bg, serializer);
    sse_encode_opt_String(self.bgm, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_list_bridge_variable(self.variables, serializer);
    sse_encode_opt_box_autoadd_bridge_step(self.current, serializer);
    sse_encode_list_bridge_step(self.history, serializer);
  }

  @protected
  void sse_encode_bridge_step(BridgeStep self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.actorName, serializer);
    sse_encode_opt_String(self.actorId, serializer);
    sse_encode_opt_String(self.emotion, serializer);
    sse_encode_opt_String(self.position, serializer);
    sse_encode_list_bridge_choice(self.choices, serializer);
  }

  @protected
  void sse_encode_bridge_variable(
    BridgeVariable self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_list_bridge_choice(
    List<BridgeChoice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_choice(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_step(
    List<BridgeStep> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_step(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_variable(
    List<BridgeVariable> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_variable(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_step(
    BridgeStep? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_step(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
